config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#home'
  get 'posts', to: "posts#index"
  get 'about', to: 'pages#about'
  get 'products', to: 'pages#products'
  resources :posts

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
     #This validates presence of title, and makes sure that the length is not more than 140 words
  validates :title, presence: true, length: {maximum: 140}
  #This validates presence of body
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:edit, :update, :show, :destroy]
      before_action :authenticate_admin!, except: [:index, :show]
  # Index action to render all posts
  def index
    @posts = Post.all
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container" id="footer">
        <small class="footer_font">
            Copyright &copy; Joaquim Grilo
        </small>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Progene Supplementos</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Blog', posts_path %></li>
        <li><%= link_to 'Produtos', products_path %></li>
        <li><%= link_to 'Sobre', about_path %></li>
        
        <% if admin_signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'My Account', edit_admin_registration_path  %></li>
          <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_admin_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Progene Supplementos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Render navigation bar -->
  <%= render "layouts/navigation" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
<footer> 
  <%=render 'layouts/footer'%>
</footer>
</body>
</html>

app/views/pages/about.html.erb
<div class = "row" align="center" id="youvideo">
          <div class ="col-12">
              <iframe align="center" width="100%" height="315" src="https://www.youtube.com/embed/AbSfKOX6n_o" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          </div>
</div>
<div class="contacte-nos">
    <p align="center"> Numero de telefone <br/> +244923446378</p>
     <p align="center"> Endereco <br/> Rua Katukelo Alvalade, Luanda</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-fluid jumbotron1" >
     <h1>Progene</h1>
     <h3>Supplementos</h3>
</div> 

<div class="container-fluid marketing circle-info">
    <section>
        <h2 align="center"> Testemunhos <br/> <br/> </h2>
         <div class="row" id="circle-info smaller-buttons">
                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 ror" align="center">
                     <%= image_tag("arnold.jpg",  alt: "arnold", class: "img-circle", width: '140', height: '140') %>
                   <h2>Arnold</h2>
                   <p> A melhor qualidade de supplementos. E a melhor staff aqui em luanda. </p>
                   <p> <%= link_to "View Details <span class='glyphicon glyphicon-menu-right' aria-hidden='true'></span>".html_safe, products_path, class: "hero-cta" %></p>
                 </div>
                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 ror" align="center" >
                     <%= image_tag("coleman.jpg",  alt: "like", class: "img-circle", width: '140', height: '140') %>
                   <h2>Coleman</h2>
                   <p>Loja essencial para todos membros do mundo de fitness!</p>
                   <p> <%= link_to "View Details <span class='glyphicon glyphicon-menu-right' aria-hidden='true'></span>".html_safe, products_path, class: "hero-cta" %></p>
                 </div>
      </div>
      </section>
         
</div>

app/views/pages/products.html.erb
<div class="container produtos" align="center">
   <div class="row ">
        <div class=" col-md-8" id='change-img'>
        </div>
        <div class="col-md-4" id='text-pic'>
            <h1 class="text-center"> Progene</h1>
            <h2 class="text-center">Produtos de alta qualidade</h2>
            <p align="center">Aqui esta lista dos produtos mais vendidos.</p>
        </div>
    </div>
</div>

<div class="container-fluid marketing" align="center">
    <div class="row" id="smaller-buttons">
                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12" id="control-vol-space" >
                     
                         <div class="squared-images" >
                             <%=image_tag("glutamine.png",  alt: "glutamine", class: "img-square") %>
                         <div class="info">
                             <p>Glutamina<br/> <br/> Prozis L-Glutamine – Aumenta os teus ganhos musculares enquanto garantes que manténs a massa muscular magra que tanto te custou a ganhar!</p>
                         </div>
                         </div><!-- /.col-lg-4 -->
                    </div>
                
                 
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12" id="control-vol-space" >
                 
                         <div class= "squared-images" >
                         <%=image_tag("taurine.jpg",  alt: "taurine", class: "img-square") %>
                         <div class="info">
                             <p>Taurine <br/> <br/> Amplamente utilizada no desporto, a taurina é uma excelente adição a uma refeição pré-treino. É também necessária à digestão de gorduras e à absorção de vitaminas lipossolúveis.<br/><br/> <%=link_to('Click here to view >', "https://alpha-blog-joaquim.herokuapp.com/", :target => "_blank" )%> </p>
                         </div>
                         </div><!-- /.col-lg-4 -->
                     
                    <!--<p align="center"> <a class="hero-cta" href="https://alpha-blog-joaquim.herokuapp.com/" role="button" > Visit Page <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a></p> -->
                </div>
                </div>
    <div class="row" id="smaller-buttons">

                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12" id="control-vol-space" >
                   
                         <div class="squared-images">
                             <%= image_tag("peanutbutter.jpg",  alt: "peanutbutter", class: "img-square")%>
                         
                         <div class="info">
                             <p>Peanut Butter <br/> <br/>In this webapp you can create a profile and follow stocks by searching with the right stock symbol. You may follow friends and see what stocks they're interested in. .<br/><br/> <%=link_to('Click here to view >', "https://finance-tracker-joaquim.herokuapp.com/", :target => "_blank" )%> </p>
                         </div>
                         </div><!-- /.col-lg-4 -->
                    
                 </div>

                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12" id="control-vol-space" >
                         <div class="squared-images">
                             <%= image_tag("protein bar.jpg", alt: "proteinbar", class: "img-square")%>
                        <div class="info"  >
                            
                             <p>Protein Bar <br/> <br/> Fonte natural de fibra e proteínas para a construção muscular, a manteiga de amendoim com pedaços de nozes pecan caramelizadas da Prozis é deliciosa para juntar aos teus snacks. Experimenta!<br/><br/> <%=link_to('Click here to view >', "https://joaquim-photo-app2.herokuapp.com/", :target => "_blank" )%> </p>
                         </div>
                         </div><!-- /.col-lg-4 -->
                   
                 </div>
      </div>

               
                 <div class="row" id="smaller-buttons">

                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12" id="control-vol-space" >
                   
                         <div class="squared-images" >
                             <%= image_tag("prozziwhey.jpg",  alt: "protein", class: "img-square")%>
                         <div class="info">
                             <p>Whey Isolate<br/> <br/>Proteína whey da mais alta qualidade, rica em BCAAs, que te vai ajudar a aumentar a tua massa muscular e a manter o músculo que te custou tanto a ganhar. "Keep it real!"<br/><br/> <%=link_to('Click here to view >', "https://deboties.herokuapp.com", :target => "_blank" )%> </p>
                         </div>
                         </div><!-- /.col-lg-4 -->
                 </div>
                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12" id="control-vol-space" >
                   
                         <div class="squared-images" >
                             <%= image_tag("shaker.jpg",  alt: "shaker", class: "img-square")%>
                         <div class="info">
                             <p>Protein Shaker<br/> <br/>Shaker Follow Your Passion<br/><br/> <%=link_to('Click here to view >', "https://deboties.herokuapp.com", :target => "_blank" )%> </p>
                         </div>
                         </div><!-- /.col-lg-4 -->
                 </div>
                 
                 </div>
                 </div>



</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>
<div class="col-xs-offset-2 col-xs-4">
<%= link_to "Cancel", posts_path %>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html.erb
<div class="col-sm-11 col-xs-12 blog-container">
 
    <% @posts.each do |post| %>
    <div class="container-fluid">
     
        <h2 class="text-center"><%= post.title %></h2>
        <h6 class="text-center"><%= post.created_at.strftime('%b %d, %Y') %></h6>

      <div class="text-center" id="article-index">
        <%= truncate(raw(post.body), :length => 230, :omission => "" , :escape => false) %>
      </div>
      <div class="text-center">
        <%= link_to "READ MORE", post_path(post) %>
      </div>
      <% if admin_signed_in? %>
        <%= link_to "Edit", edit_post_path(post), class: "btn btn-default" %>
        <%= link_to "Delete", post_path(post), class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
      <% end %>
      <hr />
    </div>
    <% end %>

</div>

app/views/posts/new.html.erb
<h2>Create New Post</h2>

<%= render "posts/form" %>

app/views/posts/show.html.erb
<div class="col-sm-11 col-xs-12 blog-content">
  <h2 class="text-center"><%= @post.title %></h2>
  <h5 class="text-center"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <div><%= raw @post.body %></div>
  <div class="article-actions">
      <%= link_to "Blog", posts_path, class: "btn btn-success" %>
 <% if admin_signed_in? %>
        <%= link_to "Edit", edit_post_path, class: "btn btn-default" %>
        <%= link_to "Delete", post_path, class: "btn btn-danger", data: {:confirm => "Are you sure?"}, method: :delete %>
      <% end %>
   
    
</div>
</div>